FROM openjdk:8-jdk

# Set environment variables
ENV HADOOP_VERSION=3.3.5 \
    SPARK_VERSION=3.3.0 \
    HADOOP_HOME=/opt/hadoop \
    SPARK_HOME=/opt/spark \
    HADOOP_CONF_DIR=/etc/hadoop/conf \
    YARN_CONF_DIR=/etc/hadoop/conf \
    PATH=$PATH:/opt/hadoop/bin:/opt/spark/bin

# Install curl, tar, and unzip
RUN apt-get update && apt-get install -y curl tar unzip

# Install Hadoop
RUN curl -O https://downloads.apache.org/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz && \
    tar -xzf hadoop-$HADOOP_VERSION.tar.gz -C /opt && \
    ln -s /opt/hadoop-$HADOOP_VERSION /opt/hadoop && \
    rm hadoop-$HADOOP_VERSION.tar.gz

# Install Spark
RUN curl -O https://downloads.apache.org/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop3.tgz && \
    tar -xzf spark-$SPARK_VERSION-bin-hadoop3.tgz -C /opt && \
    ln -s /opt/spark-$SPARK_VERSION-bin-hadoop3 /opt/spark && \
    rm spark-$SPARK_VERSION-bin-hadoop3.tgz

# Set working directory
WORKDIR /app

# Copy the application JAR
COPY target/wine-ml-spark-1.0-SNAPSHOT.jar /app/app.jar

# Default entrypoint for Spark job
ENTRYPOINT ["/opt/spark/bin/spark-submit", "--class", "com.wine.WinePredictApp", "--master", "yarn", "/app/app.jar"]
