# Use an OpenJDK base image
FROM bitnami/spark:3.3.0

# Set the working directory
WORKDIR /app

# Copy the jar file into the container
COPY target/wine-ml-spark-1.0-SNAPSHOT.jar /app/app.jar

# Set entrypoint to run Spark job
ENTRYPOINT ["java", "-jar", "/app/wine-ml-spark-1.0-SNAPSHOT.jar"]




# Copy the JAR file into the container
COPY target/wine-ml-spark-1.0-SNAPSHOT.jar /app/app.jar

# Entry point to run the prediction
ENTRYPOINT ["/opt/bitnami/spark/bin/spark-submit", "--class", "com.wine.WinePredictApp", "--master", "local[*]", "/app/app.jar"]

